[package]
name = "simple_queue"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
bincode = "1.3.3"
crossbeam = { version = "0.8.4", features = ["crossbeam-queue"] }
tokio = { version = "1.39.1", features = ["full"] }
